// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ClimbingLogContext))]
    [Migration("20260507002027_AddGradeSystemAndSeedAchievements")]
    partial class AddGradeSystemAndSeedAchievements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Achievements.AchievementDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GradeSystem")
                        .HasColumnType("text");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AchievementDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Condition = 0,
                            Description = "Log your first ascent.",
                            Threshold = 1,
                            Title = "First Steps"
                        },
                        new
                        {
                            Id = 2,
                            Condition = 0,
                            Description = "Log 10 ascents.",
                            Threshold = 10,
                            Title = "Getting Started"
                        },
                        new
                        {
                            Id = 3,
                            Condition = 0,
                            Description = "Log 100 ascents.",
                            Threshold = 100,
                            Title = "Century Climber"
                        },
                        new
                        {
                            Id = 4,
                            Condition = 0,
                            Description = "Log 500 ascents.",
                            Threshold = 500,
                            Title = "Dedicated"
                        },
                        new
                        {
                            Id = 5,
                            Condition = 1,
                            Description = "Complete your first session.",
                            Threshold = 1,
                            Title = "First Session"
                        },
                        new
                        {
                            Id = 6,
                            Condition = 1,
                            Description = "Complete 10 sessions.",
                            Threshold = 10,
                            Title = "Regular"
                        },
                        new
                        {
                            Id = 7,
                            Condition = 1,
                            Description = "Complete 50 sessions.",
                            Threshold = 50,
                            Title = "Committed"
                        },
                        new
                        {
                            Id = 8,
                            Condition = 1,
                            Description = "Complete 100 sessions.",
                            Threshold = 100,
                            Title = "Veteran"
                        },
                        new
                        {
                            Id = 9,
                            Condition = 3,
                            Description = "Climb 100 meters total.",
                            Threshold = 100,
                            Title = "First Steps Up"
                        },
                        new
                        {
                            Id = 10,
                            Condition = 3,
                            Description = "Climb 1,000 meters total.",
                            Threshold = 1000,
                            Title = "High Achiever"
                        },
                        new
                        {
                            Id = 11,
                            Condition = 3,
                            Description = "Climb 8,849 meters total.",
                            Threshold = 8849,
                            Title = "Everest"
                        },
                        new
                        {
                            Id = 12,
                            Condition = 2,
                            Description = "Send a V5 or harder.",
                            GradeSystem = "VScale",
                            Threshold = 6,
                            Title = "Getting Serious"
                        },
                        new
                        {
                            Id = 13,
                            Condition = 2,
                            Description = "Send a V7 or harder.",
                            GradeSystem = "VScale",
                            Threshold = 8,
                            Title = "Intermediate"
                        },
                        new
                        {
                            Id = 14,
                            Condition = 2,
                            Description = "Send a V9 or harder.",
                            GradeSystem = "VScale",
                            Threshold = 10,
                            Title = "Advanced"
                        },
                        new
                        {
                            Id = 15,
                            Condition = 2,
                            Description = "Send a V10 or harder.",
                            GradeSystem = "VScale",
                            Threshold = 11,
                            Title = "Double Digit"
                        },
                        new
                        {
                            Id = 16,
                            Condition = 2,
                            Description = "Send a 5.11a or harder.",
                            GradeSystem = "YDS",
                            Threshold = 9,
                            Title = "Getting Serious"
                        },
                        new
                        {
                            Id = 17,
                            Condition = 2,
                            Description = "Send a 5.12a or harder.",
                            GradeSystem = "YDS",
                            Threshold = 13,
                            Title = "Intermediate"
                        },
                        new
                        {
                            Id = 18,
                            Condition = 2,
                            Description = "Send a 5.13a or harder.",
                            GradeSystem = "YDS",
                            Threshold = 17,
                            Title = "Advanced"
                        },
                        new
                        {
                            Id = 19,
                            Condition = 2,
                            Description = "Send a 5.14a or harder.",
                            GradeSystem = "YDS",
                            Threshold = 21,
                            Title = "Elite"
                        },
                        new
                        {
                            Id = 20,
                            Condition = 2,
                            Description = "Send a 7a or harder.",
                            GradeSystem = "French",
                            Threshold = 15,
                            Title = "Getting Serious"
                        },
                        new
                        {
                            Id = 21,
                            Condition = 2,
                            Description = "Send a 7c or harder.",
                            GradeSystem = "French",
                            Threshold = 19,
                            Title = "Intermediate"
                        },
                        new
                        {
                            Id = 22,
                            Condition = 2,
                            Description = "Send an 8b or harder.",
                            GradeSystem = "French",
                            Threshold = 23,
                            Title = "Advanced"
                        },
                        new
                        {
                            Id = 23,
                            Condition = 2,
                            Description = "Send a 9a or harder.",
                            GradeSystem = "French",
                            Threshold = 27,
                            Title = "Elite"
                        });
                });

            modelBuilder.Entity("api.Models.Achievements.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementDefinitionId");

                    b.HasIndex("UserId", "AchievementDefinitionId")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("api.Models.Ascent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GradeRank")
                        .HasColumnType("integer");

                    b.Property<string>("GradeSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Ascents");
                });

            modelBuilder.Entity("api.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("api.Models.Achievements.UserAchievement", b =>
                {
                    b.HasOne("api.Models.Achievements.AchievementDefinition", "AchievementDefinition")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AchievementDefinition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Ascent", b =>
                {
                    b.HasOne("api.Models.Session", "Session")
                        .WithMany("Ascents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("api.Models.Session", b =>
                {
                    b.HasOne("api.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Achievements.AchievementDefinition", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("api.Models.Session", b =>
                {
                    b.Navigation("Ascents");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("UserAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
